apiVersion: v1
kind: Service
metadata:
  name: {{ include "divetracx.fullname" . }}
  labels:
    {{- include "divetracx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ ternary "gate" "http" .Values.hodor.enabled }}
      protocol: TCP
  selector:
    {{- include "divetracx.selectorLabels" . | nindent 4 }}
