import { Download, FileCode2, FileJson2, ShieldAlert, Table2 } from 'lucide-react'
import type { ComponentType } from 'react'

interface ExportOption {
  title: string
  description: string
  details: string
  href: string
  label: string
  icon: ComponentType<{ size?: number; className?: string; 'aria-hidden'?: boolean }>
}

const exportOptions: ExportOption[] = [
  {
    title: 'Divetracx backup',
    description: 'A complete, versioned copy of your Divetracx database records.',
    details:
      'JSON · dives, sites, people, equipment, tanks, picture references, certifications, and sync history',
    href: '/api/export/json',
    label: 'Download JSON',
    icon: FileJson2,
  },
  {
    title: 'Dive spreadsheet',
    description: 'One joined row per dive for spreadsheets and data analysis.',
    details: 'CSV · UTF-8 with sites, buddies, equipment, tanks, and measurements',
    href: '/api/export/csv',
    label: 'Download CSV',
    icon: Table2,
  },
  {
    title: 'Universal dive log',
    description: 'A portable logbook for software that supports the UDDF standard.',
    details: 'UDDF 3.2.3 · SI units, diver details, sites, and high-level dive data',
    href: '/api/export/uddf',
    label: 'Download UDDF',
    icon: FileCode2,
  },
]

export function ExportPage() {
  return (
    <div className="mx-auto max-w-4xl space-y-7">
      <header>
        <p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">
          Settings
        </p>
        <h1 className="mt-2 text-4xl font-semibold tracking-tight">Export data</h1>
        <p className="mt-3 max-w-2xl leading-7 text-muted-foreground">
          Keep an independent backup, open your dives in a spreadsheet, or move your
          logbook to another compatible application.
        </p>
      </header>

      <section className="grid gap-4 lg:grid-cols-3">
        {exportOptions.map((option) => (
          <article
            key={option.href}
            className="flex flex-col rounded-2xl border border-border bg-card p-6"
          >
            <span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary">
              <option.icon size={21} aria-hidden={true} />
            </span>
            <h2 className="mt-5 text-lg font-semibold">{option.title}</h2>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">
              {option.description}
            </p>
            <p className="mt-4 text-xs leading-5 text-muted-foreground">
              {option.details}
            </p>
            <a
              href={option.href}
              download
              className="mt-6 inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/20 transition hover:opacity-90 lg:mt-auto lg:translate-y-2"
            >
              <Download size={16} aria-hidden="true" />
              {option.label}
            </a>
          </article>
        ))}
      </section>

      <aside className="flex gap-4 rounded-2xl border border-amber-500/25 bg-amber-500/5 p-5">
        <ShieldAlert
          className="mt-0.5 shrink-0 text-amber-600"
          size={22}
          aria-hidden="true"
        />
        <div>
          <h2 className="font-semibold">Treat exports as personal data</h2>
          <p className="mt-1 text-sm leading-6 text-muted-foreground">
            Downloads can contain contact details, locations, health information, and
            private notes. Store them securely and delete copies you no longer need.
          </p>
        </div>
      </aside>

      <p className="text-sm leading-6 text-muted-foreground">
        DiveMate&apos;s native <code>.ddb</code> format is proprietary and is not
        generated by this export. UDDF is the best choice for moving dives into another
        logbook; JSON is the lossless Divetracx backup.
      </p>
    </div>
  )
}
