/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DivesIndexRouteImport } from './routes/dives/index'
import { Route as SettingsSyncIndexRouteImport } from './routes/settings/sync/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DivesIndexRoute = DivesIndexRouteImport.update({
  id: '/dives/',
  path: '/dives/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncIndexRoute = SettingsSyncIndexRouteImport.update({
  id: '/settings/sync/',
  path: '/settings/sync/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dives/': typeof DivesIndexRoute
  '/settings/sync/': typeof SettingsSyncIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dives': typeof DivesIndexRoute
  '/settings/sync': typeof SettingsSyncIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dives/': typeof DivesIndexRoute
  '/settings/sync/': typeof SettingsSyncIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dives/' | '/settings/sync/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dives' | '/settings/sync'
  id: '__root__' | '/' | '/dives/' | '/settings/sync/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DivesIndexRoute: typeof DivesIndexRoute
  SettingsSyncIndexRoute: typeof SettingsSyncIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dives/': {
      id: '/dives/'
      path: '/dives'
      fullPath: '/dives/'
      preLoaderRoute: typeof DivesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync/': {
      id: '/settings/sync/'
      path: '/settings/sync'
      fullPath: '/settings/sync/'
      preLoaderRoute: typeof SettingsSyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DivesIndexRoute: DivesIndexRoute,
  SettingsSyncIndexRoute: SettingsSyncIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
