/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as DivesIndexRouteImport } from './routes/dives/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as ApiExportCsvRouteImport } from './routes/api/export/csv'
import { Route as ApiExportJsonRouteImport } from './routes/api/export/json'
import { Route as ApiExportUddfRouteImport } from './routes/api/export/uddf'
import { Route as DataEntityIndexRouteImport } from './routes/data/$entity/index'
import { Route as DivesDiveIdIndexRouteImport } from './routes/dives/$diveId/index'
import { Route as SettingsExportIndexRouteImport } from './routes/settings/export/index'
import { Route as SettingsSyncIndexRouteImport } from './routes/settings/sync/index'
import { Route as DataEntityRecordIdIndexRouteImport } from './routes/data/$entity/$recordId/index'
import { Route as SettingsSyncLogsIndexRouteImport } from './routes/settings/sync/logs/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DivesIndexRoute = DivesIndexRouteImport.update({
  id: '/dives/',
  path: '/dives/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportCsvRoute = ApiExportCsvRouteImport.update({
  id: '/api/export/csv',
  path: '/api/export/csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportJsonRoute = ApiExportJsonRouteImport.update({
  id: '/api/export/json',
  path: '/api/export/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportUddfRoute = ApiExportUddfRouteImport.update({
  id: '/api/export/uddf',
  path: '/api/export/uddf',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEntityIndexRoute = DataEntityIndexRouteImport.update({
  id: '/data/$entity/',
  path: '/data/$entity/',
  getParentRoute: () => rootRouteImport,
} as any)
const DivesDiveIdIndexRoute = DivesDiveIdIndexRouteImport.update({
  id: '/dives/$diveId/',
  path: '/dives/$diveId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExportIndexRoute = SettingsExportIndexRouteImport.update({
  id: '/settings/export/',
  path: '/settings/export/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncIndexRoute = SettingsSyncIndexRouteImport.update({
  id: '/settings/sync/',
  path: '/settings/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEntityRecordIdIndexRoute = DataEntityRecordIdIndexRouteImport.update({
  id: '/data/$entity/$recordId/',
  path: '/data/$entity/$recordId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncLogsIndexRoute = SettingsSyncLogsIndexRouteImport.update({
  id: '/settings/sync/logs/',
  path: '/settings/sync/logs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/data/': typeof DataIndexRoute
  '/dives/': typeof DivesIndexRoute
  '/map/': typeof MapIndexRoute
  '/api/export/csv': typeof ApiExportCsvRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/uddf': typeof ApiExportUddfRoute
  '/data/$entity/': typeof DataEntityIndexRoute
  '/dives/$diveId/': typeof DivesDiveIdIndexRoute
  '/settings/export/': typeof SettingsExportIndexRoute
  '/settings/sync/': typeof SettingsSyncIndexRoute
  '/data/$entity/$recordId/': typeof DataEntityRecordIdIndexRoute
  '/settings/sync/logs/': typeof SettingsSyncLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/data': typeof DataIndexRoute
  '/dives': typeof DivesIndexRoute
  '/map': typeof MapIndexRoute
  '/api/export/csv': typeof ApiExportCsvRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/uddf': typeof ApiExportUddfRoute
  '/data/$entity': typeof DataEntityIndexRoute
  '/dives/$diveId': typeof DivesDiveIdIndexRoute
  '/settings/export': typeof SettingsExportIndexRoute
  '/settings/sync': typeof SettingsSyncIndexRoute
  '/data/$entity/$recordId': typeof DataEntityRecordIdIndexRoute
  '/settings/sync/logs': typeof SettingsSyncLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/data/': typeof DataIndexRoute
  '/dives/': typeof DivesIndexRoute
  '/map/': typeof MapIndexRoute
  '/api/export/csv': typeof ApiExportCsvRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/uddf': typeof ApiExportUddfRoute
  '/data/$entity/': typeof DataEntityIndexRoute
  '/dives/$diveId/': typeof DivesDiveIdIndexRoute
  '/settings/export/': typeof SettingsExportIndexRoute
  '/settings/sync/': typeof SettingsSyncIndexRoute
  '/data/$entity/$recordId/': typeof DataEntityRecordIdIndexRoute
  '/settings/sync/logs/': typeof SettingsSyncLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/data/'
    | '/dives/'
    | '/map/'
    | '/api/export/csv'
    | '/api/export/json'
    | '/api/export/uddf'
    | '/data/$entity/'
    | '/dives/$diveId/'
    | '/settings/export/'
    | '/settings/sync/'
    | '/data/$entity/$recordId/'
    | '/settings/sync/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/data'
    | '/dives'
    | '/map'
    | '/api/export/csv'
    | '/api/export/json'
    | '/api/export/uddf'
    | '/data/$entity'
    | '/dives/$diveId'
    | '/settings/export'
    | '/settings/sync'
    | '/data/$entity/$recordId'
    | '/settings/sync/logs'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/data/'
    | '/dives/'
    | '/map/'
    | '/api/export/csv'
    | '/api/export/json'
    | '/api/export/uddf'
    | '/data/$entity/'
    | '/dives/$diveId/'
    | '/settings/export/'
    | '/settings/sync/'
    | '/data/$entity/$recordId/'
    | '/settings/sync/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DataIndexRoute: typeof DataIndexRoute
  DivesIndexRoute: typeof DivesIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  ApiExportCsvRoute: typeof ApiExportCsvRoute
  ApiExportJsonRoute: typeof ApiExportJsonRoute
  ApiExportUddfRoute: typeof ApiExportUddfRoute
  DataEntityIndexRoute: typeof DataEntityIndexRoute
  DivesDiveIdIndexRoute: typeof DivesDiveIdIndexRoute
  SettingsExportIndexRoute: typeof SettingsExportIndexRoute
  SettingsSyncIndexRoute: typeof SettingsSyncIndexRoute
  DataEntityRecordIdIndexRoute: typeof DataEntityRecordIdIndexRoute
  SettingsSyncLogsIndexRoute: typeof SettingsSyncLogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dives/': {
      id: '/dives/'
      path: '/dives'
      fullPath: '/dives/'
      preLoaderRoute: typeof DivesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/csv': {
      id: '/api/export/csv'
      path: '/api/export/csv'
      fullPath: '/api/export/csv'
      preLoaderRoute: typeof ApiExportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/json': {
      id: '/api/export/json'
      path: '/api/export/json'
      fullPath: '/api/export/json'
      preLoaderRoute: typeof ApiExportJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/uddf': {
      id: '/api/export/uddf'
      path: '/api/export/uddf'
      fullPath: '/api/export/uddf'
      preLoaderRoute: typeof ApiExportUddfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$entity/': {
      id: '/data/$entity/'
      path: '/data/$entity'
      fullPath: '/data/$entity/'
      preLoaderRoute: typeof DataEntityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dives/$diveId/': {
      id: '/dives/$diveId/'
      path: '/dives/$diveId'
      fullPath: '/dives/$diveId/'
      preLoaderRoute: typeof DivesDiveIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/export/': {
      id: '/settings/export/'
      path: '/settings/export'
      fullPath: '/settings/export/'
      preLoaderRoute: typeof SettingsExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync/': {
      id: '/settings/sync/'
      path: '/settings/sync'
      fullPath: '/settings/sync/'
      preLoaderRoute: typeof SettingsSyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$entity/$recordId/': {
      id: '/data/$entity/$recordId/'
      path: '/data/$entity/$recordId'
      fullPath: '/data/$entity/$recordId/'
      preLoaderRoute: typeof DataEntityRecordIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync/logs/': {
      id: '/settings/sync/logs/'
      path: '/settings/sync/logs'
      fullPath: '/settings/sync/logs/'
      preLoaderRoute: typeof SettingsSyncLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  DataIndexRoute: DataIndexRoute,
  DivesIndexRoute: DivesIndexRoute,
  MapIndexRoute: MapIndexRoute,
  ApiExportCsvRoute: ApiExportCsvRoute,
  ApiExportJsonRoute: ApiExportJsonRoute,
  ApiExportUddfRoute: ApiExportUddfRoute,
  DataEntityIndexRoute: DataEntityIndexRoute,
  DivesDiveIdIndexRoute: DivesDiveIdIndexRoute,
  SettingsExportIndexRoute: SettingsExportIndexRoute,
  SettingsSyncIndexRoute: SettingsSyncIndexRoute,
  DataEntityRecordIdIndexRoute: DataEntityRecordIdIndexRoute,
  SettingsSyncLogsIndexRoute: SettingsSyncLogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
